application: extreme-passkey-104622
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: unit_4.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest